//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class GfQuaternion : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GfQuaternion(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GfQuaternion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GfQuaternion() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_GfQuaternion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public GfQuaternion() : this(USDIPCPINVOKE.new_GfQuaternion__SWIG_0(), true) {
  }

  public GfQuaternion(int realVal) : this(USDIPCPINVOKE.new_GfQuaternion__SWIG_1(realVal), true) {
  }

  public GfQuaternion(double real, GfVec3d imaginary) : this(USDIPCPINVOKE.new_GfQuaternion__SWIG_2(real, GfVec3d.getCPtr(imaginary)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetReal(double real) {
    USDIPCPINVOKE.GfQuaternion_SetReal(swigCPtr, real);
  }

  public void SetImaginary(GfVec3d imaginary) {
    USDIPCPINVOKE.GfQuaternion_SetImaginary(swigCPtr, GfVec3d.getCPtr(imaginary));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetReal() {
    double ret = USDIPCPINVOKE.GfQuaternion_GetReal(swigCPtr);
    return ret;
  }

  public GfVec3d GetImaginary() {
    GfVec3d ret = new GfVec3d(USDIPCPINVOKE.GfQuaternion_GetImaginary(swigCPtr), false);
    return ret;
  }

  public static GfQuaternion GetIdentity() {
    GfQuaternion ret = new GfQuaternion(USDIPCPINVOKE.GfQuaternion_GetIdentity(), true);
    return ret;
  }

  public double GetLength() {
    double ret = USDIPCPINVOKE.GfQuaternion_GetLength(swigCPtr);
    return ret;
  }

  public GfQuaternion GetNormalized(double eps) {
    GfQuaternion ret = new GfQuaternion(USDIPCPINVOKE.GfQuaternion_GetNormalized__SWIG_0(swigCPtr, eps), true);
    return ret;
  }

  public GfQuaternion GetNormalized() {
    GfQuaternion ret = new GfQuaternion(USDIPCPINVOKE.GfQuaternion_GetNormalized__SWIG_1(swigCPtr), true);
    return ret;
  }

  public double Normalize(double eps) {
    double ret = USDIPCPINVOKE.GfQuaternion_Normalize__SWIG_0(swigCPtr, eps);
    return ret;
  }

  public double Normalize() {
    double ret = USDIPCPINVOKE.GfQuaternion_Normalize__SWIG_1(swigCPtr);
    return ret;
  }

  public GfQuaternion GetInverse() {
    GfQuaternion ret = new GfQuaternion(USDIPCPINVOKE.GfQuaternion_GetInverse(swigCPtr), true);
    return ret;
  }

  public static bool Equals(GfQuaternion lhs, GfQuaternion rhs) {
    bool ret = USDIPCPINVOKE.GfQuaternion_Equals(GfQuaternion.getCPtr(lhs), GfQuaternion.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  override public int GetHashCode() {
    int ret = USDIPCPINVOKE.GfQuaternion_GetHashCode(swigCPtr);
    return ret;
  }

    public static bool operator==(GfQuaternion lhs, GfQuaternion rhs){
      // The Swig binding glue will re-enter this operator comparing to null, so 
      // that case must be handled explicitly to avoid an infinite loop. This is still
      // not great, since it crosses the C#/C++ barrier twice. A better approache might
      // be to return a simple value from C++ that can be compared in C#.
      bool lnull = lhs as object == null;
      bool rnull = rhs as object == null;
      return (lnull == rnull) && ((lnull && rnull) || GfQuaternion.Equals(lhs, rhs));
    }

    public static bool operator !=(GfQuaternion lhs, GfQuaternion rhs) {
        return !(lhs == rhs);
    }

    override public bool Equals(object rhs) {
      return GfQuaternion.Equals(this, rhs as GfQuaternion);
    }
  
}

}
