//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class SdfAssetPathArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SdfAssetPathArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.SdfAssetPathArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SdfAssetPathArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SdfAssetPathArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_SdfAssetPathArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public SdfAssetPath this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public SdfAssetPathArray() : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_0(), true) {
  }

  public SdfAssetPathArray(Vt_ArrayForeignDataSource foreignSrc, SdfAssetPath data, uint size, bool addRef) : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SdfAssetPath.getCPtr(data), size, addRef), true) {
  }

  public SdfAssetPathArray(Vt_ArrayForeignDataSource foreignSrc, SdfAssetPath data, uint size) : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SdfAssetPath.getCPtr(data), size), true) {
  }

  public SdfAssetPathArray(SdfAssetPathArray other) : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_3(SdfAssetPathArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SdfAssetPathArray(uint n, SdfAssetPath value) : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_5(n, SdfAssetPath.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SdfAssetPathArray(uint n) : this(USDIPCPINVOKE.new_SdfAssetPathArray__SWIG_6(n), true) {
  }

  public void push_back(SdfAssetPath elem) {
    USDIPCPINVOKE.SdfAssetPathArray_push_back(swigCPtr, SdfAssetPath.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.SdfAssetPathArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.SdfAssetPathArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.SdfAssetPathArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.SdfAssetPathArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.SdfAssetPathArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.SdfAssetPathArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.SdfAssetPathArray_clear(swigCPtr);
  }

  public void assign(uint n, SdfAssetPath fill) {
    USDIPCPINVOKE.SdfAssetPathArray_assign(swigCPtr, n, SdfAssetPath.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(SdfAssetPathArray other) {
    USDIPCPINVOKE.SdfAssetPathArray_swap(swigCPtr, SdfAssetPathArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(SdfAssetPathArray other) {
    bool ret = USDIPCPINVOKE.SdfAssetPathArray_IsIdentical(swigCPtr, SdfAssetPathArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(SdfAssetPathArray lhs, SdfAssetPathArray rhs) {
    bool ret = USDIPCPINVOKE.SdfAssetPathArray_Equals(SdfAssetPathArray.getCPtr(lhs), SdfAssetPathArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.SdfAssetPathArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(SdfAssetPath[] dest) {
    USDIPCPINVOKE.SdfAssetPathArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(SdfAssetPath[] src) {
    USDIPCPINVOKE.SdfAssetPathArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.SdfAssetPathArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.SdfAssetPathArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected SdfAssetPath GetValue(int index) {
    SdfAssetPath ret = new SdfAssetPath(USDIPCPINVOKE.SdfAssetPathArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, SdfAssetPath value) {
    USDIPCPINVOKE.SdfAssetPathArray_SetValue(swigCPtr, index, SdfAssetPath.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
