//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class SdfLayer : SdfLayerBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SdfLayer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.SdfLayer_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SdfLayer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SdfLayer() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          USDIPCPINVOKE.delete_SdfLayer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static SdfLayer CreateNew(string identifier, string realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_0(identifier, realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args));
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateNew(string identifier, string realPath) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_1(identifier, realPath);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateNew(string identifier) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_2(identifier);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateNew(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier, string realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_3(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier, realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args));
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateNew(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier, string realPath) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_4(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier, realPath);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateNew(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateNew__SWIG_5(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer New(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier, string realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_New__SWIG_0(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier, realPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args));
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer New(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier, string realPath) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_New__SWIG_1(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier, realPath);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer New(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr fileFormat, string identifier) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_New__SWIG_2(SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(fileFormat), identifier);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayerHandle Find(string identifier, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    SdfLayerHandle ret = new SdfLayerHandle(USDIPCPINVOKE.SdfLayer_Find__SWIG_0(identifier, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayerHandle Find(string identifier) {
    SdfLayerHandle ret = new SdfLayerHandle(USDIPCPINVOKE.SdfLayer_Find__SWIG_1(identifier), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayerHandle FindRelativeToLayer(SdfLayerHandle anchor, string layerPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    SdfLayerHandle ret = new SdfLayerHandle(USDIPCPINVOKE.SdfLayer_FindRelativeToLayer__SWIG_0(SdfLayerHandle.getCPtr(anchor), layerPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayerHandle FindRelativeToLayer(SdfLayerHandle anchor, string layerPath) {
    SdfLayerHandle ret = new SdfLayerHandle(USDIPCPINVOKE.SdfLayer_FindRelativeToLayer__SWIG_1(SdfLayerHandle.getCPtr(anchor), layerPath), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer FindOrOpen(string identifier, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_FindOrOpen__SWIG_0(identifier, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args));
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer FindOrOpen(string identifier) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_FindOrOpen__SWIG_1(identifier);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer OpenAsAnonymous(string layerPath, bool metadataOnly, string tag) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_OpenAsAnonymous__SWIG_0(layerPath, metadataOnly, tag);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer OpenAsAnonymous(string layerPath, bool metadataOnly) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_OpenAsAnonymous__SWIG_1(layerPath, metadataOnly);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer OpenAsAnonymous(string layerPath) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_OpenAsAnonymous__SWIG_2(layerPath);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SWIGTYPE_p_SdfSchemaBase GetSchema() {
    SWIGTYPE_p_SdfSchemaBase ret = new SWIGTYPE_p_SdfSchemaBase(USDIPCPINVOKE.SdfLayer_GetSchema(swigCPtr), false);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_SdfLayerHandleSet GetLoadedLayers() {
    SWIGTYPE_p_SdfLayerHandleSet ret = new SWIGTYPE_p_SdfLayerHandleSet(USDIPCPINVOKE.SdfLayer_GetLoadedLayers(), true);
    return ret;
  }

  public bool IsEmpty() {
    bool ret = USDIPCPINVOKE.SdfLayer_IsEmpty(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void TransferContent(SdfLayerHandle layer) {
    USDIPCPINVOKE.SdfLayer_TransferContent(swigCPtr, SdfLayerHandle.getCPtr(layer));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SdfLayer CreateAnonymous(string tag) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateAnonymous__SWIG_0(tag);
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SdfLayer CreateAnonymous() {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateAnonymous__SWIG_1();
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    return ret;
  }

  public static SdfLayer CreateAnonymous(string tag, SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr format) {
    global::System.IntPtr cPtr = USDIPCPINVOKE.SdfLayer_CreateAnonymous__SWIG_2(tag, SWIGTYPE_p_TfDeclarePtrsT_SdfFileFormat_t__ConstPtr.getCPtr(format));
    SdfLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SdfLayer(cPtr, true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsAnonymous() {
    bool ret = USDIPCPINVOKE.SdfLayer_IsAnonymous(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool IsAnonymousLayerIdentifier(string identifier) {
    bool ret = USDIPCPINVOKE.SdfLayer_IsAnonymousLayerIdentifier(identifier);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string GetDisplayNameFromIdentifier(string identifier) {
    string ret = USDIPCPINVOKE.SdfLayer_GetDisplayNameFromIdentifier(identifier);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string ComputeRealPath(string layerPath) {
    string ret = USDIPCPINVOKE.SdfLayer_ComputeRealPath(layerPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Save(bool force) {
    bool ret = USDIPCPINVOKE.SdfLayer_Save__SWIG_0(swigCPtr, force);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Save() {
    bool ret = USDIPCPINVOKE.SdfLayer_Save__SWIG_1(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Export(string filename, string comment, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t args) {
    bool ret = USDIPCPINVOKE.SdfLayer_Export__SWIG_0(swigCPtr, filename, comment, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(args));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Export(string filename, string comment) {
    bool ret = USDIPCPINVOKE.SdfLayer_Export__SWIG_1(swigCPtr, filename, comment);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Export(string filename) {
    bool ret = USDIPCPINVOKE.SdfLayer_Export__SWIG_2(swigCPtr, filename);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ImportFromString(string arg0) {
    bool ret = USDIPCPINVOKE.SdfLayer_ImportFromString(swigCPtr, arg0);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Clear() {
    USDIPCPINVOKE.SdfLayer_Clear(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Reload(bool force) {
    bool ret = USDIPCPINVOKE.SdfLayer_Reload__SWIG_0(swigCPtr, force);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Reload() {
    bool ret = USDIPCPINVOKE.SdfLayer_Reload__SWIG_1(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool ReloadLayers(SWIGTYPE_p_std__setT_SdfLayerHandle_t layers, bool force) {
    bool ret = USDIPCPINVOKE.SdfLayer_ReloadLayers__SWIG_0(SWIGTYPE_p_std__setT_SdfLayerHandle_t.getCPtr(layers), force);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool ReloadLayers(SWIGTYPE_p_std__setT_SdfLayerHandle_t layers) {
    bool ret = USDIPCPINVOKE.SdfLayer_ReloadLayers__SWIG_1(SWIGTYPE_p_std__setT_SdfLayerHandle_t.getCPtr(layers));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Import(string layerPath) {
    bool ret = USDIPCPINVOKE.SdfLayer_Import(swigCPtr, layerPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__setT_std__string_t GetExternalReferences() {
    SWIGTYPE_p_std__setT_std__string_t ret = new SWIGTYPE_p_std__setT_std__string_t(USDIPCPINVOKE.SdfLayer_GetExternalReferences(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool UpdateExternalReference(string oldAssetPath, string newAssetPath) {
    bool ret = USDIPCPINVOKE.SdfLayer_UpdateExternalReference__SWIG_0(swigCPtr, oldAssetPath, newAssetPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool UpdateExternalReference(string oldAssetPath) {
    bool ret = USDIPCPINVOKE.SdfLayer_UpdateExternalReference__SWIG_1(swigCPtr, oldAssetPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool SplitIdentifier(string identifier, SWIGTYPE_p_std__string layerPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t arguments) {
    bool ret = USDIPCPINVOKE.SdfLayer_SplitIdentifier(identifier, SWIGTYPE_p_std__string.getCPtr(layerPath), SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(arguments));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string CreateIdentifier(string layerPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t arguments) {
    string ret = USDIPCPINVOKE.SdfLayer_CreateIdentifier(layerPath, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(arguments));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetIdentifier() {
    string ret = USDIPCPINVOKE.SdfLayer_GetIdentifier(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIdentifier(string identifier) {
    USDIPCPINVOKE.SdfLayer_SetIdentifier(swigCPtr, identifier);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UpdateAssetInfo(string fileVersion) {
    USDIPCPINVOKE.SdfLayer_UpdateAssetInfo__SWIG_0(swigCPtr, fileVersion);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UpdateAssetInfo() {
    USDIPCPINVOKE.SdfLayer_UpdateAssetInfo__SWIG_1(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetDisplayName() {
    string ret = USDIPCPINVOKE.SdfLayer_GetDisplayName(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetRealPath() {
    string ret = USDIPCPINVOKE.SdfLayer_GetRealPath(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetFileExtension() {
    string ret = USDIPCPINVOKE.SdfLayer_GetFileExtension(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetVersion() {
    string ret = USDIPCPINVOKE.SdfLayer_GetVersion(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetRepositoryPath() {
    string ret = USDIPCPINVOKE.SdfLayer_GetRepositoryPath(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetAssetName() {
    string ret = USDIPCPINVOKE.SdfLayer_GetAssetName(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VtValue GetAssetInfo() {
    VtValue ret = new VtValue(USDIPCPINVOKE.SdfLayer_GetAssetInfo(swigCPtr), false);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string ComputeAbsolutePath(string relativePath) {
    string ret = USDIPCPINVOKE.SdfLayer_ComputeAbsolutePath(swigCPtr, relativePath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__type_info GetFieldTypeid(SWIGTYPE_p_SdfAbstractDataSpecId id, TfToken name) {
    SWIGTYPE_p_std__type_info ret = new SWIGTYPE_p_std__type_info(USDIPCPINVOKE.SdfLayer_GetFieldTypeid__SWIG_0(swigCPtr, SWIGTYPE_p_SdfAbstractDataSpecId.getCPtr(id), TfToken.getCPtr(name)), false);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SdfSpecType GetSpecType(SdfPath path) {
    SdfSpecType ret = (SdfSpecType)USDIPCPINVOKE.SdfLayer_GetSpecType(swigCPtr, SdfPath.getCPtr(path));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasSpec(SdfPath path) {
    bool ret = USDIPCPINVOKE.SdfLayer_HasSpec(swigCPtr, SdfPath.getCPtr(path));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TfTokenVector ListFields(SdfPath path) {
    TfTokenVector ret = new TfTokenVector(USDIPCPINVOKE.SdfLayer_ListFields(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasField(SdfPath path, TfToken fieldName) {
    bool ret = USDIPCPINVOKE.SdfLayer_HasField(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__type_info GetFieldTypeid(SdfPath path, TfToken fieldName) {
    SWIGTYPE_p_std__type_info ret = new SWIGTYPE_p_std__type_info(USDIPCPINVOKE.SdfLayer_GetFieldTypeid__SWIG_1(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName)), false);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasFieldDictKey(SdfPath path, TfToken fieldName, TfToken keyPath) {
    bool ret = USDIPCPINVOKE.SdfLayer_HasFieldDictKey(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName), TfToken.getCPtr(keyPath));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VtValue GetField(SdfPath path, TfToken fieldName) {
    VtValue ret = new VtValue(USDIPCPINVOKE.SdfLayer_GetField(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VtValue GetFieldDictValueByKey(SdfPath path, TfToken fieldName, TfToken keyPath) {
    VtValue ret = new VtValue(USDIPCPINVOKE.SdfLayer_GetFieldDictValueByKey(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName), TfToken.getCPtr(keyPath)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EraseField(SdfPath path, TfToken fieldName) {
    USDIPCPINVOKE.SdfLayer_EraseField(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void EraseFieldDictValueByKey(SdfPath path, TfToken fieldName, TfToken keyPath) {
    USDIPCPINVOKE.SdfLayer_EraseFieldDictValueByKey(swigCPtr, SdfPath.getCPtr(path), TfToken.getCPtr(fieldName), TfToken.getCPtr(keyPath));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SdfAssetPath GetColorConfiguration() {
    SdfAssetPath ret = new SdfAssetPath(USDIPCPINVOKE.SdfLayer_GetColorConfiguration(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetColorConfiguration(SdfAssetPath colorConfiguration) {
    USDIPCPINVOKE.SdfLayer_SetColorConfiguration(swigCPtr, SdfAssetPath.getCPtr(colorConfiguration));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasColorConfiguration() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasColorConfiguration(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearColorConfiguration() {
    USDIPCPINVOKE.SdfLayer_ClearColorConfiguration(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public TfToken GetColorManagementSystem() {
    TfToken ret = new TfToken(USDIPCPINVOKE.SdfLayer_GetColorManagementSystem(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetColorManagementSystem(TfToken cms) {
    USDIPCPINVOKE.SdfLayer_SetColorManagementSystem(swigCPtr, TfToken.getCPtr(cms));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasColorManagementSystem() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasColorManagementSystem(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearColorManagementSystem() {
    USDIPCPINVOKE.SdfLayer_ClearColorManagementSystem(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetComment() {
    string ret = USDIPCPINVOKE.SdfLayer_GetComment(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetComment(string comment) {
    USDIPCPINVOKE.SdfLayer_SetComment(swigCPtr, comment);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public TfToken GetDefaultPrim() {
    TfToken ret = new TfToken(USDIPCPINVOKE.SdfLayer_GetDefaultPrim(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDefaultPrim(TfToken name) {
    USDIPCPINVOKE.SdfLayer_SetDefaultPrim(swigCPtr, TfToken.getCPtr(name));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearDefaultPrim() {
    USDIPCPINVOKE.SdfLayer_ClearDefaultPrim(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasDefaultPrim() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasDefaultPrim(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetDocumentation() {
    string ret = USDIPCPINVOKE.SdfLayer_GetDocumentation(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDocumentation(string documentation) {
    USDIPCPINVOKE.SdfLayer_SetDocumentation(swigCPtr, documentation);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetStartTimeCode() {
    double ret = USDIPCPINVOKE.SdfLayer_GetStartTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStartTimeCode(double startTimecode) {
    USDIPCPINVOKE.SdfLayer_SetStartTimeCode(swigCPtr, startTimecode);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasStartTimeCode() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasStartTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearStartTimeCode() {
    USDIPCPINVOKE.SdfLayer_ClearStartTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetEndTimeCode() {
    double ret = USDIPCPINVOKE.SdfLayer_GetEndTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetEndTimeCode(double endTimeCode) {
    USDIPCPINVOKE.SdfLayer_SetEndTimeCode(swigCPtr, endTimeCode);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasEndTimeCode() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasEndTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearEndTimeCode() {
    USDIPCPINVOKE.SdfLayer_ClearEndTimeCode(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetTimeCodesPerSecond() {
    double ret = USDIPCPINVOKE.SdfLayer_GetTimeCodesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTimeCodesPerSecond(double timeCodesPerSecond) {
    USDIPCPINVOKE.SdfLayer_SetTimeCodesPerSecond(swigCPtr, timeCodesPerSecond);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasTimeCodesPerSecond() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasTimeCodesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearTimeCodesPerSecond() {
    USDIPCPINVOKE.SdfLayer_ClearTimeCodesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetFramesPerSecond() {
    double ret = USDIPCPINVOKE.SdfLayer_GetFramesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFramesPerSecond(double framesPerSecond) {
    USDIPCPINVOKE.SdfLayer_SetFramesPerSecond(swigCPtr, framesPerSecond);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasFramesPerSecond() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasFramesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearFramesPerSecond() {
    USDIPCPINVOKE.SdfLayer_ClearFramesPerSecond(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetFramePrecision() {
    int ret = USDIPCPINVOKE.SdfLayer_GetFramePrecision(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFramePrecision(int framePrecision) {
    USDIPCPINVOKE.SdfLayer_SetFramePrecision(swigCPtr, framePrecision);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasFramePrecision() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasFramePrecision(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearFramePrecision() {
    USDIPCPINVOKE.SdfLayer_ClearFramePrecision(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetOwner() {
    string ret = USDIPCPINVOKE.SdfLayer_GetOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOwner(string owner) {
    USDIPCPINVOKE.SdfLayer_SetOwner(swigCPtr, owner);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasOwner() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearOwner() {
    USDIPCPINVOKE.SdfLayer_ClearOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetSessionOwner() {
    string ret = USDIPCPINVOKE.SdfLayer_GetSessionOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSessionOwner(string owner) {
    USDIPCPINVOKE.SdfLayer_SetSessionOwner(swigCPtr, owner);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasSessionOwner() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasSessionOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearSessionOwner() {
    USDIPCPINVOKE.SdfLayer_ClearSessionOwner(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetHasOwnedSubLayers() {
    bool ret = USDIPCPINVOKE.SdfLayer_GetHasOwnedSubLayers(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetHasOwnedSubLayers(bool arg0) {
    USDIPCPINVOKE.SdfLayer_SetHasOwnedSubLayers(swigCPtr, arg0);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtDictionary GetCustomLayerData() {
    VtDictionary ret = new VtDictionary(USDIPCPINVOKE.SdfLayer_GetCustomLayerData(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCustomLayerData(VtDictionary value) {
    USDIPCPINVOKE.SdfLayer_SetCustomLayerData(swigCPtr, VtDictionary.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasCustomLayerData() {
    bool ret = USDIPCPINVOKE.SdfLayer_HasCustomLayerData(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ClearCustomLayerData() {
    USDIPCPINVOKE.SdfLayer_ClearCustomLayerData(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SdfPrimSpecView GetRootPrims() {
    SWIGTYPE_p_SdfPrimSpecView ret = new SWIGTYPE_p_SdfPrimSpecView(USDIPCPINVOKE.SdfLayer_GetRootPrims(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRootPrims(SWIGTYPE_p_SdfPrimSpecHandleVector rootPrims) {
    USDIPCPINVOKE.SdfLayer_SetRootPrims(swigCPtr, SWIGTYPE_p_SdfPrimSpecHandleVector.getCPtr(rootPrims));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool InsertRootPrim(SWIGTYPE_p_SdfPrimSpecHandle prim, int index) {
    bool ret = USDIPCPINVOKE.SdfLayer_InsertRootPrim__SWIG_0(swigCPtr, SWIGTYPE_p_SdfPrimSpecHandle.getCPtr(prim), index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool InsertRootPrim(SWIGTYPE_p_SdfPrimSpecHandle prim) {
    bool ret = USDIPCPINVOKE.SdfLayer_InsertRootPrim__SWIG_1(swigCPtr, SWIGTYPE_p_SdfPrimSpecHandle.getCPtr(prim));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void RemoveRootPrim(SWIGTYPE_p_SdfPrimSpecHandle prim) {
    USDIPCPINVOKE.SdfLayer_RemoveRootPrim(swigCPtr, SWIGTYPE_p_SdfPrimSpecHandle.getCPtr(prim));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ScheduleRemoveIfInert(SWIGTYPE_p_SdfSpec spec) {
    USDIPCPINVOKE.SdfLayer_ScheduleRemoveIfInert(swigCPtr, SWIGTYPE_p_SdfSpec.getCPtr(spec));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemovePrimIfInert(SWIGTYPE_p_SdfPrimSpecHandle prim) {
    USDIPCPINVOKE.SdfLayer_RemovePrimIfInert(swigCPtr, SWIGTYPE_p_SdfPrimSpecHandle.getCPtr(prim));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemovePropertyIfHasOnlyRequiredFields(SWIGTYPE_p_SdfPropertySpecHandle prop) {
    USDIPCPINVOKE.SdfLayer_RemovePropertyIfHasOnlyRequiredFields(swigCPtr, SWIGTYPE_p_SdfPropertySpecHandle.getCPtr(prop));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveInertSceneDescription() {
    USDIPCPINVOKE.SdfLayer_RemoveInertSceneDescription(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRootPrimOrder(TfTokenVector names) {
    USDIPCPINVOKE.SdfLayer_SetRootPrimOrder(swigCPtr, TfTokenVector.getCPtr(names));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertInRootPrimOrder(TfToken name, int index) {
    USDIPCPINVOKE.SdfLayer_InsertInRootPrimOrder__SWIG_0(swigCPtr, TfToken.getCPtr(name), index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertInRootPrimOrder(TfToken name) {
    USDIPCPINVOKE.SdfLayer_InsertInRootPrimOrder__SWIG_1(swigCPtr, TfToken.getCPtr(name));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveFromRootPrimOrder(TfToken name) {
    USDIPCPINVOKE.SdfLayer_RemoveFromRootPrimOrder(swigCPtr, TfToken.getCPtr(name));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveFromRootPrimOrderByIndex(int index) {
    USDIPCPINVOKE.SdfLayer_RemoveFromRootPrimOrderByIndex(swigCPtr, index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ApplyRootPrimOrder(TfTokenVector vec) {
    USDIPCPINVOKE.SdfLayer_ApplyRootPrimOrder(swigCPtr, TfTokenVector.getCPtr(vec));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSubLayerPaths(StdStringVector newPaths) {
    USDIPCPINVOKE.SdfLayer_SetSubLayerPaths(swigCPtr, StdStringVector.getCPtr(newPaths));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumSubLayerPaths() {
    uint ret = USDIPCPINVOKE.SdfLayer_GetNumSubLayerPaths(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void InsertSubLayerPath(string path, int index) {
    USDIPCPINVOKE.SdfLayer_InsertSubLayerPath__SWIG_0(swigCPtr, path, index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertSubLayerPath(string path) {
    USDIPCPINVOKE.SdfLayer_InsertSubLayerPath__SWIG_1(swigCPtr, path);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveSubLayerPath(int index) {
    USDIPCPINVOKE.SdfLayer_RemoveSubLayerPath(swigCPtr, index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SdfLayerOffsetVector GetSubLayerOffsets() {
    SdfLayerOffsetVector ret = new SdfLayerOffsetVector(USDIPCPINVOKE.SdfLayer_GetSubLayerOffsets(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SdfLayerOffset GetSubLayerOffset(int index) {
    SdfLayerOffset ret = new SdfLayerOffset(USDIPCPINVOKE.SdfLayer_GetSubLayerOffset(swigCPtr, index), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSubLayerOffset(SdfLayerOffset offset, int index) {
    USDIPCPINVOKE.SdfLayer_SetSubLayerOffset(swigCPtr, SdfLayerOffset.getCPtr(offset), index);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_std__setT_std__string_t GetMutedLayers() {
    SWIGTYPE_p_std__setT_std__string_t ret = new SWIGTYPE_p_std__setT_std__string_t(USDIPCPINVOKE.SdfLayer_GetMutedLayers(), true);
    return ret;
  }

  public bool IsMuted() {
    bool ret = USDIPCPINVOKE.SdfLayer_IsMuted__SWIG_0(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool IsMuted(string path) {
    bool ret = USDIPCPINVOKE.SdfLayer_IsMuted__SWIG_1(path);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMuted(bool muted) {
    USDIPCPINVOKE.SdfLayer_SetMuted(swigCPtr, muted);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void AddToMutedLayers(string mutedPath) {
    USDIPCPINVOKE.SdfLayer_AddToMutedLayers(mutedPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void RemoveFromMutedLayers(string mutedPath) {
    USDIPCPINVOKE.SdfLayer_RemoveFromMutedLayers(mutedPath);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_SdfPrimSpecHandle GetPseudoRoot() {
    SWIGTYPE_p_SdfPrimSpecHandle ret = new SWIGTYPE_p_SdfPrimSpecHandle(USDIPCPINVOKE.SdfLayer_GetPseudoRoot(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_SdfSpecHandle GetObjectAtPath(SdfPath path) {
    SWIGTYPE_p_SdfSpecHandle ret = new SWIGTYPE_p_SdfSpecHandle(USDIPCPINVOKE.SdfLayer_GetObjectAtPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_SdfPrimSpecHandle GetPrimAtPath(SdfPath path) {
    SWIGTYPE_p_SdfPrimSpecHandle ret = new SWIGTYPE_p_SdfPrimSpecHandle(USDIPCPINVOKE.SdfLayer_GetPrimAtPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_SdfPropertySpecHandle GetPropertyAtPath(SdfPath path) {
    SWIGTYPE_p_SdfPropertySpecHandle ret = new SWIGTYPE_p_SdfPropertySpecHandle(USDIPCPINVOKE.SdfLayer_GetPropertyAtPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_SdfAttributeSpecHandle GetAttributeAtPath(SdfPath path) {
    SWIGTYPE_p_SdfAttributeSpecHandle ret = new SWIGTYPE_p_SdfAttributeSpecHandle(USDIPCPINVOKE.SdfLayer_GetAttributeAtPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_SdfRelationshipSpecHandle GetRelationshipAtPath(SdfPath path) {
    SWIGTYPE_p_SdfRelationshipSpecHandle ret = new SWIGTYPE_p_SdfRelationshipSpecHandle(USDIPCPINVOKE.SdfLayer_GetRelationshipAtPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool PermissionToEdit() {
    bool ret = USDIPCPINVOKE.SdfLayer_PermissionToEdit(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool PermissionToSave() {
    bool ret = USDIPCPINVOKE.SdfLayer_PermissionToSave(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPermissionToEdit(bool allow) {
    USDIPCPINVOKE.SdfLayer_SetPermissionToEdit(swigCPtr, allow);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPermissionToSave(bool allow) {
    USDIPCPINVOKE.SdfLayer_SetPermissionToSave(swigCPtr, allow);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public SdfNamespaceEditDetail.Result CanApply(SdfBatchNamespaceEdit arg0, SdfNamespaceEditDetailVector details) {
    SdfNamespaceEditDetail.Result ret = (SdfNamespaceEditDetail.Result)USDIPCPINVOKE.SdfLayer_CanApply__SWIG_0(swigCPtr, SdfBatchNamespaceEdit.getCPtr(arg0), SdfNamespaceEditDetailVector.getCPtr(details));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SdfNamespaceEditDetail.Result CanApply(SdfBatchNamespaceEdit arg0) {
    SdfNamespaceEditDetail.Result ret = (SdfNamespaceEditDetail.Result)USDIPCPINVOKE.SdfLayer_CanApply__SWIG_1(swigCPtr, SdfBatchNamespaceEdit.getCPtr(arg0));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Apply(SdfBatchNamespaceEdit arg0) {
    bool ret = USDIPCPINVOKE.SdfLayer_Apply(swigCPtr, SdfBatchNamespaceEdit.getCPtr(arg0));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_TfDeclarePtrsT_SdfLayerStateDelegateBase_t__Ptr GetStateDelegate() {
    SWIGTYPE_p_TfDeclarePtrsT_SdfLayerStateDelegateBase_t__Ptr ret = new SWIGTYPE_p_TfDeclarePtrsT_SdfLayerStateDelegateBase_t__Ptr(USDIPCPINVOKE.SdfLayer_GetStateDelegate(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStateDelegate(SWIGTYPE_p_TfDeclarePtrsT_SdfLayerStateDelegateBase_t__RefPtr arg0) {
    USDIPCPINVOKE.SdfLayer_SetStateDelegate(swigCPtr, SWIGTYPE_p_TfDeclarePtrsT_SdfLayerStateDelegateBase_t__RefPtr.getCPtr(arg0));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsDirty() {
    bool ret = USDIPCPINVOKE.SdfLayer_IsDirty(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__setT_double_t ListAllTimeSamples() {
    SWIGTYPE_p_std__setT_double_t ret = new SWIGTYPE_p_std__setT_double_t(USDIPCPINVOKE.SdfLayer_ListAllTimeSamples(swigCPtr), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetBracketingTimeSamples(double time, ref double tLower, ref double tUpper) {
    bool ret = USDIPCPINVOKE.SdfLayer_GetBracketingTimeSamples(swigCPtr, time, ref tLower, ref tUpper);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetNumTimeSamplesForPath(SdfPath path) {
    uint ret = USDIPCPINVOKE.SdfLayer_GetNumTimeSamplesForPath(swigCPtr, SdfPath.getCPtr(path));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__setT_double_t ListTimeSamplesForPath(SdfPath path) {
    SWIGTYPE_p_std__setT_double_t ret = new SWIGTYPE_p_std__setT_double_t(USDIPCPINVOKE.SdfLayer_ListTimeSamplesForPath(swigCPtr, SdfPath.getCPtr(path)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetBracketingTimeSamplesForPath(SdfPath path, double time, ref double tLower, ref double tUpper) {
    bool ret = USDIPCPINVOKE.SdfLayer_GetBracketingTimeSamplesForPath(swigCPtr, SdfPath.getCPtr(path), time, ref tLower, ref tUpper);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool QueryTimeSample(SdfPath path, double time) {
    bool ret = USDIPCPINVOKE.SdfLayer_QueryTimeSample(swigCPtr, SdfPath.getCPtr(path), time);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EraseTimeSample(SdfPath path, double time) {
    USDIPCPINVOKE.SdfLayer_EraseTimeSample(swigCPtr, SdfPath.getCPtr(path), time);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void DumpLayerInfo() {
    USDIPCPINVOKE.SdfLayer_DumpLayerInfo();
  }

  public bool WriteDataFile(string filename) {
    bool ret = USDIPCPINVOKE.SdfLayer_WriteDataFile(swigCPtr, filename);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string ExportToString() {
    string ret = USDIPCPINVOKE.SdfLayer_ExportToString(swigCPtr);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
