//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class UsdGeomFaceSetAPI : UsdSchemaBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal UsdGeomFaceSetAPI(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.UsdGeomFaceSetAPI_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UsdGeomFaceSetAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UsdGeomFaceSetAPI() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_UsdGeomFaceSetAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public UsdGeomFaceSetAPI(UsdPrim prim, TfToken setName) : this(USDIPCPINVOKE.new_UsdGeomFaceSetAPI__SWIG_0(UsdPrim.getCPtr(prim), TfToken.getCPtr(setName)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public UsdGeomFaceSetAPI(UsdPrim prim) : this(USDIPCPINVOKE.new_UsdGeomFaceSetAPI__SWIG_1(UsdPrim.getCPtr(prim)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public UsdGeomFaceSetAPI() : this(USDIPCPINVOKE.new_UsdGeomFaceSetAPI__SWIG_2(), true) {
  }

  public UsdGeomFaceSetAPI(UsdSchemaBase schemaObj, TfToken setName) : this(USDIPCPINVOKE.new_UsdGeomFaceSetAPI__SWIG_3(UsdSchemaBase.getCPtr(schemaObj), TfToken.getCPtr(setName)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public TfToken GetFaceSetName() {
    TfToken ret = new TfToken(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceSetName(swigCPtr), true);
    return ret;
  }

  public bool SetIsPartition(bool isPartition) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetIsPartition(swigCPtr, isPartition);
    return ret;
  }

  public bool GetIsPartition() {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetIsPartition(swigCPtr);
    return ret;
  }

  public bool SetFaceCounts(VtIntArray faceCounts, UsdTimeCode time) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetFaceCounts__SWIG_0(swigCPtr, VtIntArray.getCPtr(faceCounts), UsdTimeCode.getCPtr(time));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool SetFaceCounts(VtIntArray faceCounts) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetFaceCounts__SWIG_1(swigCPtr, VtIntArray.getCPtr(faceCounts));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetFaceCounts(VtIntArray faceCounts, UsdTimeCode time) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceCounts__SWIG_0(swigCPtr, VtIntArray.getCPtr(faceCounts), UsdTimeCode.getCPtr(time));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetFaceCounts(VtIntArray faceCounts) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceCounts__SWIG_1(swigCPtr, VtIntArray.getCPtr(faceCounts));
    return ret;
  }

  public bool SetFaceIndices(VtIntArray faceIndices, UsdTimeCode time) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetFaceIndices__SWIG_0(swigCPtr, VtIntArray.getCPtr(faceIndices), UsdTimeCode.getCPtr(time));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool SetFaceIndices(VtIntArray faceIndices) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetFaceIndices__SWIG_1(swigCPtr, VtIntArray.getCPtr(faceIndices));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetFaceIndices(VtIntArray faceIndices, UsdTimeCode time) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceIndices__SWIG_0(swigCPtr, VtIntArray.getCPtr(faceIndices), UsdTimeCode.getCPtr(time));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetFaceIndices(VtIntArray faceIndices) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceIndices__SWIG_1(swigCPtr, VtIntArray.getCPtr(faceIndices));
    return ret;
  }

  public bool SetBindingTargets(SdfPathVector bindings) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_SetBindingTargets(swigCPtr, SdfPathVector.getCPtr(bindings));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetBindingTargets(SdfPathVector bindings) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_GetBindingTargets(swigCPtr, SdfPathVector.getCPtr(bindings));
    return ret;
  }

  public bool AppendFaceGroup(VtIntArray faceIndices, SdfPath bindingTarget, UsdTimeCode time) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_AppendFaceGroup__SWIG_0(swigCPtr, VtIntArray.getCPtr(faceIndices), SdfPath.getCPtr(bindingTarget), UsdTimeCode.getCPtr(time));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool AppendFaceGroup(VtIntArray faceIndices, SdfPath bindingTarget) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_AppendFaceGroup__SWIG_1(swigCPtr, VtIntArray.getCPtr(faceIndices), SdfPath.getCPtr(bindingTarget));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool AppendFaceGroup(VtIntArray faceIndices) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_AppendFaceGroup__SWIG_2(swigCPtr, VtIntArray.getCPtr(faceIndices));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute GetIsPartitionAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetIsPartitionAttr(swigCPtr), true);
    return ret;
  }

  public UsdAttribute CreateIsPartitionAttr(VtValue defaultValue, bool writeSparsely) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateIsPartitionAttr__SWIG_0(swigCPtr, VtValue.getCPtr(defaultValue), writeSparsely), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateIsPartitionAttr(VtValue defaultValue) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateIsPartitionAttr__SWIG_1(swigCPtr, VtValue.getCPtr(defaultValue)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateIsPartitionAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateIsPartitionAttr__SWIG_2(swigCPtr), true);
    return ret;
  }

  public UsdAttribute GetFaceCountsAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceCountsAttr(swigCPtr), true);
    return ret;
  }

  public UsdAttribute CreateFaceCountsAttr(VtValue defaultValue, bool writeSparsely) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceCountsAttr__SWIG_0(swigCPtr, VtValue.getCPtr(defaultValue), writeSparsely), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateFaceCountsAttr(VtValue defaultValue) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceCountsAttr__SWIG_1(swigCPtr, VtValue.getCPtr(defaultValue)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateFaceCountsAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceCountsAttr__SWIG_2(swigCPtr), true);
    return ret;
  }

  public UsdAttribute GetFaceIndicesAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceIndicesAttr(swigCPtr), true);
    return ret;
  }

  public UsdAttribute CreateFaceIndicesAttr(VtValue defaultValue, bool writeSparsely) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceIndicesAttr__SWIG_0(swigCPtr, VtValue.getCPtr(defaultValue), writeSparsely), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateFaceIndicesAttr(VtValue defaultValue) {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceIndicesAttr__SWIG_1(swigCPtr, VtValue.getCPtr(defaultValue)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UsdAttribute CreateFaceIndicesAttr() {
    UsdAttribute ret = new UsdAttribute(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateFaceIndicesAttr__SWIG_2(swigCPtr), true);
    return ret;
  }

  public UsdRelationship GetBindingTargetsRel() {
    UsdRelationship ret = new UsdRelationship(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetBindingTargetsRel(swigCPtr), true);
    return ret;
  }

  public UsdRelationship CreateBindingTargetsRel() {
    UsdRelationship ret = new UsdRelationship(USDIPCPINVOKE.UsdGeomFaceSetAPI_CreateBindingTargetsRel(swigCPtr), true);
    return ret;
  }

  public static UsdGeomFaceSetAPI Create(UsdPrim prim, TfToken setName, bool isPartition) {
    UsdGeomFaceSetAPI ret = new UsdGeomFaceSetAPI(USDIPCPINVOKE.UsdGeomFaceSetAPI_Create__SWIG_0(UsdPrim.getCPtr(prim), TfToken.getCPtr(setName), isPartition), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UsdGeomFaceSetAPI Create(UsdPrim prim, TfToken setName) {
    UsdGeomFaceSetAPI ret = new UsdGeomFaceSetAPI(USDIPCPINVOKE.UsdGeomFaceSetAPI_Create__SWIG_1(UsdPrim.getCPtr(prim), TfToken.getCPtr(setName)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UsdGeomFaceSetAPI Create(UsdSchemaBase schemaObj, TfToken setName, bool isPartition) {
    UsdGeomFaceSetAPI ret = new UsdGeomFaceSetAPI(USDIPCPINVOKE.UsdGeomFaceSetAPI_Create__SWIG_2(UsdSchemaBase.getCPtr(schemaObj), TfToken.getCPtr(setName), isPartition), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UsdGeomFaceSetAPI Create(UsdSchemaBase schemaObj, TfToken setName) {
    UsdGeomFaceSetAPI ret = new UsdGeomFaceSetAPI(USDIPCPINVOKE.UsdGeomFaceSetAPI_Create__SWIG_3(UsdSchemaBase.getCPtr(schemaObj), TfToken.getCPtr(setName)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UsdGeomFaceSetAPIVector GetFaceSets(UsdPrim prim) {
    UsdGeomFaceSetAPIVector ret = new UsdGeomFaceSetAPIVector(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceSets__SWIG_0(UsdPrim.getCPtr(prim)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UsdGeomFaceSetAPIVector GetFaceSets(UsdSchemaBase schemaObj) {
    UsdGeomFaceSetAPIVector ret = new UsdGeomFaceSetAPIVector(USDIPCPINVOKE.UsdGeomFaceSetAPI_GetFaceSets__SWIG_1(UsdSchemaBase.getCPtr(schemaObj)), true);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Validate(/*cstype*/ out string reason) {
    bool ret = USDIPCPINVOKE.UsdGeomFaceSetAPI_Validate(swigCPtr, out reason);
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
