//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtIntArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtIntArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtIntArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtIntArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtIntArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtIntArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public int this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtIntArray() : this(USDIPCPINVOKE.new_VtIntArray__SWIG_0(), true) {
  }

  public VtIntArray(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_int data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtIntArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_int.getCPtr(data), size, addRef), true) {
  }

  public VtIntArray(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_int data, uint size) : this(USDIPCPINVOKE.new_VtIntArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_int.getCPtr(data), size), true) {
  }

  public VtIntArray(VtIntArray other) : this(USDIPCPINVOKE.new_VtIntArray__SWIG_3(VtIntArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtIntArray(uint n, int value) : this(USDIPCPINVOKE.new_VtIntArray__SWIG_5(n, value), true) {
  }

  public VtIntArray(uint n) : this(USDIPCPINVOKE.new_VtIntArray__SWIG_6(n), true) {
  }

  public void push_back(int elem) {
    USDIPCPINVOKE.VtIntArray_push_back(swigCPtr, elem);
  }

  public void pop_back() {
    USDIPCPINVOKE.VtIntArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtIntArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtIntArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtIntArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtIntArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtIntArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtIntArray_clear(swigCPtr);
  }

  public void assign(uint n, int fill) {
    USDIPCPINVOKE.VtIntArray_assign(swigCPtr, n, fill);
  }

  public void swap(VtIntArray other) {
    USDIPCPINVOKE.VtIntArray_swap(swigCPtr, VtIntArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtIntArray other) {
    bool ret = USDIPCPINVOKE.VtIntArray_IsIdentical(swigCPtr, VtIntArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtIntArray lhs, VtIntArray rhs) {
    bool ret = USDIPCPINVOKE.VtIntArray_Equals(VtIntArray.getCPtr(lhs), VtIntArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtIntArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(int[] dest) {
    USDIPCPINVOKE.VtIntArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(int[] src) {
    USDIPCPINVOKE.VtIntArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtIntArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtIntArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected int GetValue(int index) {
    int ret = USDIPCPINVOKE.VtIntArray_GetValue(swigCPtr, index);
    return ret;
  }

  protected void SetValue(int index, int value) {
    USDIPCPINVOKE.VtIntArray_SetValue(swigCPtr, index, value);
  }

}

}
