//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtQuathArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtQuathArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtQuathArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtQuathArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtQuathArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtQuathArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public GfQuath this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtQuathArray() : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_0(), true) {
  }

  public VtQuathArray(Vt_ArrayForeignDataSource foreignSrc, GfQuath data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfQuath.getCPtr(data), size, addRef), true) {
  }

  public VtQuathArray(Vt_ArrayForeignDataSource foreignSrc, GfQuath data, uint size) : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfQuath.getCPtr(data), size), true) {
  }

  public VtQuathArray(VtQuathArray other) : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_3(VtQuathArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtQuathArray(uint n, GfQuath value) : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_5(n, GfQuath.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtQuathArray(uint n) : this(USDIPCPINVOKE.new_VtQuathArray__SWIG_6(n), true) {
  }

  public void push_back(GfQuath elem) {
    USDIPCPINVOKE.VtQuathArray_push_back(swigCPtr, GfQuath.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.VtQuathArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtQuathArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtQuathArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtQuathArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtQuathArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtQuathArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtQuathArray_clear(swigCPtr);
  }

  public void assign(uint n, GfQuath fill) {
    USDIPCPINVOKE.VtQuathArray_assign(swigCPtr, n, GfQuath.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(VtQuathArray other) {
    USDIPCPINVOKE.VtQuathArray_swap(swigCPtr, VtQuathArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtQuathArray other) {
    bool ret = USDIPCPINVOKE.VtQuathArray_IsIdentical(swigCPtr, VtQuathArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtQuathArray lhs, VtQuathArray rhs) {
    bool ret = USDIPCPINVOKE.VtQuathArray_Equals(VtQuathArray.getCPtr(lhs), VtQuathArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtQuathArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(GfQuath[] dest) {
    USDIPCPINVOKE.VtQuathArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(GfQuath[] src) {
    USDIPCPINVOKE.VtQuathArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtQuathArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtQuathArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected GfQuath GetValue(int index) {
    GfQuath ret = new GfQuath(USDIPCPINVOKE.VtQuathArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, GfQuath value) {
    USDIPCPINVOKE.VtQuathArray_SetValue(swigCPtr, index, GfQuath.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
