//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtQuatfArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtQuatfArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtQuatfArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtQuatfArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtQuatfArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtQuatfArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public GfQuatf this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtQuatfArray() : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_0(), true) {
  }

  public VtQuatfArray(Vt_ArrayForeignDataSource foreignSrc, GfQuatf data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfQuatf.getCPtr(data), size, addRef), true) {
  }

  public VtQuatfArray(Vt_ArrayForeignDataSource foreignSrc, GfQuatf data, uint size) : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfQuatf.getCPtr(data), size), true) {
  }

  public VtQuatfArray(VtQuatfArray other) : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_3(VtQuatfArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtQuatfArray(uint n, GfQuatf value) : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_5(n, GfQuatf.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtQuatfArray(uint n) : this(USDIPCPINVOKE.new_VtQuatfArray__SWIG_6(n), true) {
  }

  public void push_back(GfQuatf elem) {
    USDIPCPINVOKE.VtQuatfArray_push_back(swigCPtr, GfQuatf.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.VtQuatfArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtQuatfArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtQuatfArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtQuatfArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtQuatfArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtQuatfArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtQuatfArray_clear(swigCPtr);
  }

  public void assign(uint n, GfQuatf fill) {
    USDIPCPINVOKE.VtQuatfArray_assign(swigCPtr, n, GfQuatf.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(VtQuatfArray other) {
    USDIPCPINVOKE.VtQuatfArray_swap(swigCPtr, VtQuatfArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtQuatfArray other) {
    bool ret = USDIPCPINVOKE.VtQuatfArray_IsIdentical(swigCPtr, VtQuatfArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtQuatfArray lhs, VtQuatfArray rhs) {
    bool ret = USDIPCPINVOKE.VtQuatfArray_Equals(VtQuatfArray.getCPtr(lhs), VtQuatfArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtQuatfArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(GfQuatf[] dest) {
    USDIPCPINVOKE.VtQuatfArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(GfQuatf[] src) {
    USDIPCPINVOKE.VtQuatfArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtQuatfArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtQuatfArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected GfQuatf GetValue(int index) {
    GfQuatf ret = new GfQuatf(USDIPCPINVOKE.VtQuatfArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, GfQuatf value) {
    USDIPCPINVOKE.VtQuatfArray_SetValue(swigCPtr, index, GfQuatf.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
