//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtUInt64Array : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtUInt64Array(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtUInt64Array_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtUInt64Array obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtUInt64Array() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtUInt64Array(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public ulong this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtUInt64Array() : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_0(), true) {
  }

  public VtUInt64Array(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_unsigned_long_long data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_unsigned_long_long.getCPtr(data), size, addRef), true) {
  }

  public VtUInt64Array(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_unsigned_long_long data, uint size) : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_unsigned_long_long.getCPtr(data), size), true) {
  }

  public VtUInt64Array(VtUInt64Array other) : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_3(VtUInt64Array.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtUInt64Array(uint n, ulong value) : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_5(n, value), true) {
  }

  public VtUInt64Array(uint n) : this(USDIPCPINVOKE.new_VtUInt64Array__SWIG_6(n), true) {
  }

  public void push_back(ulong elem) {
    USDIPCPINVOKE.VtUInt64Array_push_back(swigCPtr, elem);
  }

  public void pop_back() {
    USDIPCPINVOKE.VtUInt64Array_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtUInt64Array_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtUInt64Array_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtUInt64Array_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtUInt64Array_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtUInt64Array_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtUInt64Array_clear(swigCPtr);
  }

  public void assign(uint n, ulong fill) {
    USDIPCPINVOKE.VtUInt64Array_assign(swigCPtr, n, fill);
  }

  public void swap(VtUInt64Array other) {
    USDIPCPINVOKE.VtUInt64Array_swap(swigCPtr, VtUInt64Array.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtUInt64Array other) {
    bool ret = USDIPCPINVOKE.VtUInt64Array_IsIdentical(swigCPtr, VtUInt64Array.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtUInt64Array lhs, VtUInt64Array rhs) {
    bool ret = USDIPCPINVOKE.VtUInt64Array_Equals(VtUInt64Array.getCPtr(lhs), VtUInt64Array.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtUInt64Array_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(ulong[] dest) {
    USDIPCPINVOKE.VtUInt64Array_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(ulong[] src) {
    USDIPCPINVOKE.VtUInt64Array_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtUInt64Array_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtUInt64Array_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected ulong GetValue(int index) {
    ulong ret = USDIPCPINVOKE.VtUInt64Array_GetValue(swigCPtr, index);
    return ret;
  }

  protected void SetValue(int index, ulong value) {
    USDIPCPINVOKE.VtUInt64Array_SetValue(swigCPtr, index, value);
  }

}

}
