//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtUIntArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtUIntArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtUIntArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtUIntArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtUIntArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtUIntArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public uint this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtUIntArray() : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_0(), true) {
  }

  public VtUIntArray(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_unsigned_int data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_unsigned_int.getCPtr(data), size, addRef), true) {
  }

  public VtUIntArray(Vt_ArrayForeignDataSource foreignSrc, SWIGTYPE_p_unsigned_int data, uint size) : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), SWIGTYPE_p_unsigned_int.getCPtr(data), size), true) {
  }

  public VtUIntArray(VtUIntArray other) : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_3(VtUIntArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtUIntArray(uint n, uint value) : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_5(n, value), true) {
  }

  public VtUIntArray(uint n) : this(USDIPCPINVOKE.new_VtUIntArray__SWIG_6(n), true) {
  }

  public void push_back(uint elem) {
    USDIPCPINVOKE.VtUIntArray_push_back(swigCPtr, elem);
  }

  public void pop_back() {
    USDIPCPINVOKE.VtUIntArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtUIntArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtUIntArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtUIntArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtUIntArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtUIntArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtUIntArray_clear(swigCPtr);
  }

  public void assign(uint n, uint fill) {
    USDIPCPINVOKE.VtUIntArray_assign(swigCPtr, n, fill);
  }

  public void swap(VtUIntArray other) {
    USDIPCPINVOKE.VtUIntArray_swap(swigCPtr, VtUIntArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtUIntArray other) {
    bool ret = USDIPCPINVOKE.VtUIntArray_IsIdentical(swigCPtr, VtUIntArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtUIntArray lhs, VtUIntArray rhs) {
    bool ret = USDIPCPINVOKE.VtUIntArray_Equals(VtUIntArray.getCPtr(lhs), VtUIntArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtUIntArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(uint[] dest) {
    USDIPCPINVOKE.VtUIntArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(uint[] src) {
    USDIPCPINVOKE.VtUIntArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtUIntArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtUIntArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected uint GetValue(int index) {
    uint ret = USDIPCPINVOKE.VtUIntArray_GetValue(swigCPtr, index);
    return ret;
  }

  protected void SetValue(int index, uint value) {
    USDIPCPINVOKE.VtUIntArray_SetValue(swigCPtr, index, value);
  }

}

}
