//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtVec2iArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtVec2iArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtVec2iArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtVec2iArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtVec2iArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtVec2iArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public GfVec2i this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtVec2iArray() : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_0(), true) {
  }

  public VtVec2iArray(Vt_ArrayForeignDataSource foreignSrc, GfVec2i data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec2i.getCPtr(data), size, addRef), true) {
  }

  public VtVec2iArray(Vt_ArrayForeignDataSource foreignSrc, GfVec2i data, uint size) : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec2i.getCPtr(data), size), true) {
  }

  public VtVec2iArray(VtVec2iArray other) : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_3(VtVec2iArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec2iArray(uint n, GfVec2i value) : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_5(n, GfVec2i.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec2iArray(uint n) : this(USDIPCPINVOKE.new_VtVec2iArray__SWIG_6(n), true) {
  }

  public void push_back(GfVec2i elem) {
    USDIPCPINVOKE.VtVec2iArray_push_back(swigCPtr, GfVec2i.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.VtVec2iArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtVec2iArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtVec2iArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtVec2iArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtVec2iArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtVec2iArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtVec2iArray_clear(swigCPtr);
  }

  public void assign(uint n, GfVec2i fill) {
    USDIPCPINVOKE.VtVec2iArray_assign(swigCPtr, n, GfVec2i.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(VtVec2iArray other) {
    USDIPCPINVOKE.VtVec2iArray_swap(swigCPtr, VtVec2iArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtVec2iArray other) {
    bool ret = USDIPCPINVOKE.VtVec2iArray_IsIdentical(swigCPtr, VtVec2iArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtVec2iArray lhs, VtVec2iArray rhs) {
    bool ret = USDIPCPINVOKE.VtVec2iArray_Equals(VtVec2iArray.getCPtr(lhs), VtVec2iArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtVec2iArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(GfVec2i[] dest) {
    USDIPCPINVOKE.VtVec2iArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(GfVec2i[] src) {
    USDIPCPINVOKE.VtVec2iArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtVec2iArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtVec2iArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected GfVec2i GetValue(int index) {
    GfVec2i ret = new GfVec2i(USDIPCPINVOKE.VtVec2iArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, GfVec2i value) {
    USDIPCPINVOKE.VtVec2iArray_SetValue(swigCPtr, index, GfVec2i.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
