//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtVec3hArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtVec3hArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtVec3hArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtVec3hArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtVec3hArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtVec3hArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public GfVec3h this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtVec3hArray() : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_0(), true) {
  }

  public VtVec3hArray(Vt_ArrayForeignDataSource foreignSrc, GfVec3h data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec3h.getCPtr(data), size, addRef), true) {
  }

  public VtVec3hArray(Vt_ArrayForeignDataSource foreignSrc, GfVec3h data, uint size) : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec3h.getCPtr(data), size), true) {
  }

  public VtVec3hArray(VtVec3hArray other) : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_3(VtVec3hArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec3hArray(uint n, GfVec3h value) : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_5(n, GfVec3h.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec3hArray(uint n) : this(USDIPCPINVOKE.new_VtVec3hArray__SWIG_6(n), true) {
  }

  public void push_back(GfVec3h elem) {
    USDIPCPINVOKE.VtVec3hArray_push_back(swigCPtr, GfVec3h.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.VtVec3hArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtVec3hArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtVec3hArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtVec3hArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtVec3hArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtVec3hArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtVec3hArray_clear(swigCPtr);
  }

  public void assign(uint n, GfVec3h fill) {
    USDIPCPINVOKE.VtVec3hArray_assign(swigCPtr, n, GfVec3h.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(VtVec3hArray other) {
    USDIPCPINVOKE.VtVec3hArray_swap(swigCPtr, VtVec3hArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtVec3hArray other) {
    bool ret = USDIPCPINVOKE.VtVec3hArray_IsIdentical(swigCPtr, VtVec3hArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtVec3hArray lhs, VtVec3hArray rhs) {
    bool ret = USDIPCPINVOKE.VtVec3hArray_Equals(VtVec3hArray.getCPtr(lhs), VtVec3hArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtVec3hArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(GfVec3h[] dest) {
    USDIPCPINVOKE.VtVec3hArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(GfVec3h[] src) {
    USDIPCPINVOKE.VtVec3hArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtVec3hArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtVec3hArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected GfVec3h GetValue(int index) {
    GfVec3h ret = new GfVec3h(USDIPCPINVOKE.VtVec3hArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, GfVec3h value) {
    USDIPCPINVOKE.VtVec3hArray_SetValue(swigCPtr, index, GfVec3h.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
