//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pxr {

public class VtVec3iArray : Vt_ArrayBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VtVec3iArray(global::System.IntPtr cPtr, bool cMemoryOwn) : base(USDIPCPINVOKE.VtVec3iArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VtVec3iArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VtVec3iArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          USDIPCPINVOKE.delete_VtVec3iArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	  public GfVec3i this[int index] {
		  get { return GetValue(index); }
		  set { SetValue(index, value); }
	  }
  
  public VtVec3iArray() : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_0(), true) {
  }

  public VtVec3iArray(Vt_ArrayForeignDataSource foreignSrc, GfVec3i data, uint size, bool addRef) : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_1(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec3i.getCPtr(data), size, addRef), true) {
  }

  public VtVec3iArray(Vt_ArrayForeignDataSource foreignSrc, GfVec3i data, uint size) : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_2(Vt_ArrayForeignDataSource.getCPtr(foreignSrc), GfVec3i.getCPtr(data), size), true) {
  }

  public VtVec3iArray(VtVec3iArray other) : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_3(VtVec3iArray.getCPtr(other)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec3iArray(uint n, GfVec3i value) : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_5(n, GfVec3i.getCPtr(value)), true) {
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public VtVec3iArray(uint n) : this(USDIPCPINVOKE.new_VtVec3iArray__SWIG_6(n), true) {
  }

  public void push_back(GfVec3i elem) {
    USDIPCPINVOKE.VtVec3iArray_push_back(swigCPtr, GfVec3i.getCPtr(elem));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back() {
    USDIPCPINVOKE.VtVec3iArray_pop_back(swigCPtr);
  }

  public uint size() {
    uint ret = USDIPCPINVOKE.VtVec3iArray_size(swigCPtr);
    return ret;
  }

  public uint capacity() {
    uint ret = USDIPCPINVOKE.VtVec3iArray_capacity(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = USDIPCPINVOKE.VtVec3iArray_empty(swigCPtr);
    return ret;
  }

  public void reserve(uint num) {
    USDIPCPINVOKE.VtVec3iArray_reserve(swigCPtr, num);
  }

  public void resize(uint newSize) {
    USDIPCPINVOKE.VtVec3iArray_resize(swigCPtr, newSize);
  }

  public void clear() {
    USDIPCPINVOKE.VtVec3iArray_clear(swigCPtr);
  }

  public void assign(uint n, GfVec3i fill) {
    USDIPCPINVOKE.VtVec3iArray_assign(swigCPtr, n, GfVec3i.getCPtr(fill));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(VtVec3iArray other) {
    USDIPCPINVOKE.VtVec3iArray_swap(swigCPtr, VtVec3iArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsIdentical(VtVec3iArray other) {
    bool ret = USDIPCPINVOKE.VtVec3iArray_IsIdentical(swigCPtr, VtVec3iArray.getCPtr(other));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool Equals(VtVec3iArray lhs, VtVec3iArray rhs) {
    bool ret = USDIPCPINVOKE.VtVec3iArray_Equals(VtVec3iArray.getCPtr(lhs), VtVec3iArray.getCPtr(rhs));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = USDIPCPINVOKE.VtVec3iArray_ToString(swigCPtr);
    return ret;
  }

  public void CopyToArray(GfVec3i[] dest) {
    USDIPCPINVOKE.VtVec3iArray_CopyToArray__SWIG_0(swigCPtr, dest);
  }

  public void CopyFromArray(GfVec3i[] src) {
    USDIPCPINVOKE.VtVec3iArray_CopyFromArray__SWIG_0(swigCPtr, src);
  }

  public void CopyToArray(System.IntPtr dest) {
    USDIPCPINVOKE.VtVec3iArray_CopyToArray__SWIG_1(swigCPtr, dest);
  }

  public void CopyFromArray(System.IntPtr src) {
    USDIPCPINVOKE.VtVec3iArray_CopyFromArray__SWIG_1(swigCPtr, src);
  }

  protected GfVec3i GetValue(int index) {
    GfVec3i ret = new GfVec3i(USDIPCPINVOKE.VtVec3iArray_GetValue(swigCPtr, index), false);
    return ret;
  }

  protected void SetValue(int index, GfVec3i value) {
    USDIPCPINVOKE.VtVec3iArray_SetValue(swigCPtr, index, GfVec3i.getCPtr(value));
    if (USDIPCPINVOKE.SWIGPendingException.Pending) throw USDIPCPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
